development:
  adapter: mysql2
  encoding: utf8
  database: sportsbook_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: sportsbook_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: sportsbook_production
  pool: 5
  username: root
  password:
  host: ''