# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94dea86e6a765468860101271b872d0920edf053892af91ef92f93aa18e2f5ed15194f040c4fd4085ce10988059274219086c5d007f660d9094d6b97aed1d8a6

test:
  secret_key_base: 10f8739e832d2e38d2aac1de1604b43beec522bc74fe93d50b231ccf8eb75ff87e6ea362df294db28a91f4de2c3abe6037602a7adde3fd5dc3592f1e8f2b19df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
